---

apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: s3.csi.aws.com
spec:
  attachRequired: false
  tokenRequests:
    - audience: "sts.amazonaws.com"
      expirationSeconds: 3600
  requiresRepublish: true
