---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1200Gi  # Ignored, required
  accessModes:
    - ReadWriteMany  # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: ""  # Required for static provisioning
  claimRef:  # To ensure no other PVCs can claim this PV
    namespace: default  # Namespace is required even for "default" namespace.
    name: s3-pvc  # Name of your PVC
  mountOptions:
    - allow-overwrite  # Test workload will replace files
    - region=us-west-2
    - otlp-endpoint=http://cloudwatch-agent.amazon-cloudwatch.svc.cluster.local:4318
  csi:
    driver: s3.csi.aws.com  # Required
    volumeHandle: s3-csi-driver-volume  # Must be unique
    volumeAttributes:
      bucketName: amzn-s3-demo-bucket
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
spec:
  accessModes:
    - ReadWriteMany  # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: ""  # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi  # Ignored, required
  volumeName: s3-pv  # Name of your PV
---
apiVersion: v1
kind: Pod
metadata:
  name: mountpoint-example-app-otlp
spec:
  containers:
    - name: app
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo \"$(date -u): Hello from pod $HOSTNAME\" > /data/$HOSTNAME.txt; cat /data/$HOSTNAME.txt; sleep 2; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: s3-pvc
