apiVersion: v2
name: aws-mountpoint-s3-csi-driver
description: A Helm chart for installing the Mountpoint for Amazon S3 CSI Driver. This CSI driver allows your Kubernetes applications to access S3 objects through a file system interface.
version: 1.15.0
kubeVersion: ">=1.25.0-0"
home: https://github.com/awslabs/mountpoint-s3-csi-driver
sources:
  - https://github.com/awslabs/mountpoint-s3-csi-driver
keywords:
  - aws
  - mountpoint
  - s3
  - csi
maintainers:
  - name: AWS S3
    url: https://github.com/awslabs/mountpoint-s3-csi-driver
