{{- if .Values.experimental.podMounter -}}

{{- if .Values.controller.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.controller.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
  {{- with .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-role
  namespace: {{ .Values.mountpointPod.namespace }}
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "watch", "delete", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-role-binding
  namespace: {{ .Values.mountpointPod.namespace }}
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: s3-csi-driver-controller-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-cluster-role
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "persistentvolumes"]
    verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: s3-csi-driver-controller-cluster-role-binding
  labels:
    {{- include "aws-mountpoint-s3-csi-driver.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: s3-csi-driver-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}

{{- end -}}
