on:
  workflow_call:
    outputs:
      matrix:
        description: "Matrix"
        value: ${{ jobs.build_matrix.outputs.matrix }}

permissions:
  contents: read

jobs:
  build_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.parse_yaml.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - name: Parse matrix.yaml file
        id: parse_yaml
        run: |
            echo "matrix=$(yq -P -o=json '.matrix' '.github/matrix.yaml' | jq -c)" >> $GITHUB_OUTPUT
