name: Controller tests

on:
  push:
    branches: ["main", "feature/*"]
  pull_request:
    branches: ["main", "feature/*"]
  merge_group:
    types: ["checks_requested"]

permissions:
  contents: read

jobs:
  build_matrix:
    name: Build Matrix
    uses: ./.github/workflows/build_matrix.yaml

  controller_test:
    needs: ["build_matrix"]
    strategy:
      matrix:
        kubernetes-version: ${{ fromJson(needs.build_matrix.outputs.matrix)['kubernetes-version'] }}
    runs-on: ubuntu-latest
    env:
      # envtest doesn't support all versions, here K8S_VERSION is a full version like 1.28.13,
      # and in order to get latest supported version by envtest we convert it to 1.28.
      K8S_VERSION: "${{ matrix.kubernetes-version }}"
      ENVTEST_K8S_VERSION: "${K8S_VERSION%.*}"
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Run Controller Tests
        run: |
          make e2e-controller

  post_test:
    needs: controller_test
    runs-on: ubuntu-latest
    steps:
      - name: Controller tests completed
        run: echo "All controller tests passed"
